version: '3.8'
services:
  db:
    image: mongo
    env_file: ./env/db.env
    ports:
      - 27017:27017
    volumes:
      - ~/mongo/data:/data/db
  backend:
    build: ./backend
    env_file: ./env/backend.env
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
    command: ['flask', 'run']
  frontend:
    build: frontend
    command: ['npm', 'start']
    volumes:
      - ./frontend:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - backend
  mongo-express:
    image: mongo-express
    env_file: ./env/mongo-express.env
    depends_on:
      - db
    ports:
      - 8081:8081
volumes:
  node-modules:
